
name: cashcontrol_app
description: CashControl App
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: true
